version: '3.4'

services:
  chatwarden:
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    image: ${DOCKER_REGISTRY-}chatwarden
    restart: always
    hostname: cw
    container_name: CW
    build:
      context: .
      dockerfile: ChatWarden/Dockerfile
    environment:
      TARANTOOL_CNNSTR: "${TARANTOOL_USER}:${TARANTOOL_PWD}@${TARANTOOL_HOST}:${TARANTOOL_INTERNAL_PORT}"
      TOKEN: "${TOKEN}"

  tarantool:
    container_name: Tarantool
    hostname: ${TARANTOOL_HOST}
    build:
      context: ChatWarden/Infrastructure/Tarantool
      dockerfile: Dockerfile
        
    ports:
      - ${TARANTOOL_EXTERNAL_PORT}:${TARANTOOL_INTERNAL_PORT}
      - 8081:8081
    environment:
      TARANTOOL_USER_NAME: ${TARANTOOL_USER}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_PWD}